name: Publish Docker image

on:
  release:
    types: ['published']

env:
  REGISTRY: git.gay
  IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push-image:
      runs-on: docker
      steps:
        - name: Checkout repository
          uses: https://code.forgejo.org/actions/checkout@v4
        
        - name: Log in to the Container registry
          uses: https://github.com/docker/login-action@v1
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.REGISTRY_TOKEN }}
        
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: https://github.com/docker/metadata-action@v3
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        
        - name: Build and push Docker image
          uses: https://github.com/docker/build-push-action@v2
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}